### ISSUE TITLE
Images tags rendered as strings and not as HTML

### ISSUE THREAD

**Issue by wachunei** [proyectoSuchai/proyectoSuchai.github.io#4]
Template tags are not rendering HTML and the output is a string containing tags.

<img width="756" alt="screen shot 2016-03-22 at 11 28 51 am" src="https://cloud.githubusercontent.com/assets/1024246/13954938/9342b08a-f021-11e5-84b8-47c4681f4050.png">

**Comment by toopazo** [comment]
Thank you for communicating with us about the problem, we have fixed it. 

We are mainly electrical engineer, so web development is not part of our strengths.

Regards

**Comment by carlgonz** [comment]
Thanks! It's seems to be a problem with recent versions of Jekyll and GitHub pages
